import type { DeliveryReport, DistillResult, SinkPlugin } from "@loamlog/core";

export interface NotionSinkConfig {
  /** Notion integration token. Falls back to NOTION_TOKEN env var. */
  token?: string;
  /** Target Notion database ID (UUID with or without hyphens). Falls back to NOTION_DATABASE_ID env var. */
  databaseId?: string;
  /** Dry run mode: log what would be created without calling the API. */
  dryRun?: boolean;
}

class NotionAPIError extends Error {
  status: number;
  constructor(message: string, status: number) {
    super(message);
    this.name = "NotionAPIError";
    this.status = status;
  }
}

async function createNotionPage(
  token: string,
  databaseId: string,
  properties: Record<string, unknown>,
  children: unknown[],
): Promise<{ url: string }> {
  const url = "https://api.notion.com/v1/pages";
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "Notion-Version": "2022-06-28",
    },
    body: JSON.stringify({
      parent: { database_id: databaseId },
      properties,
      children,
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    let message = `Notion API error ${response.status}`;
    try {
      const parsed = JSON.parse(text) as { message?: string };
      if (parsed.message) message = parsed.message;
    } catch {
      message = text.slice(0, 300);
    }
    throw new NotionAPIError(message, response.status);
  }

  const page = (await response.json()) as { url?: string; id?: string };
  return { url: page.url ?? `https://notion.so/${(page.id ?? "").replace(/-/g, "")}` };
}

function buildPageProperties(result: DistillResult): Record<string, unknown> {
  return {
    Name: {
      title: [{ text: { content: result.title.slice(0, 2000) } }],
    },
    Summary: {
      rich_text: [{ text: { content: result.summary.slice(0, 2000) } }],
    },
    Type: {
      select: { name: result.type },
    },
    Confidence: {
      number: Math.round(result.confidence * 100) / 100,
    },
    Tags: {
      multi_select: result.tags.slice(0, 10).map((tag) => ({ name: tag.slice(0, 100) })),
    },
  };
}

function buildPageChildren(result: DistillResult): unknown[] {
  const blocks: unknown[] = [];

  // Evidence section heading
  blocks.push({
    object: "block",
    type: "heading_2",
    heading_2: {
      rich_text: [{ type: "text", text: { content: "Evidence" } }],
    },
  });

  for (const evidence of result.evidence) {
    blocks.push({
      object: "block",
      type: "paragraph",
      paragraph: {
        rich_text: [
          {
            type: "text",
            text: {
              content: `${evidence.excerpt.slice(0, 500)}\n— Session \`${evidence.session_id}\` / Message \`${evidence.message_id}\``,
            },
          },
        ],
      },
    });
  }

  // Footer
  blocks.push({
    object: "block",
    type: "divider",
    divider: {},
  });
  blocks.push({
    object: "block",
    type: "paragraph",
    paragraph: {
      rich_text: [
        {
          type: "text",
          text: {
            content: `Generated by Loamlog @ ${result.distiller_id}`,
          },
        },
      ],
    },
  });

  return blocks;
}

export function createNotionSink(config: NotionSinkConfig = {}): SinkPlugin {
  return {
    id: "@loamlog/sink-notion",
    name: "Notion Database Sink",
    version: "0.1.0",

    supports(resultType: string): boolean {
      return ["issue-draft", "prd-draft", "knowledge-card", "pitfall-card"].includes(resultType);
    },

    async deliver(input: {
      results: DistillResult[];
      config: Record<string, unknown>;
    }): Promise<DeliveryReport> {
      const merged: NotionSinkConfig = { ...config, ...(input.config as NotionSinkConfig) };
      const token = merged.token ?? process.env.NOTION_TOKEN;
      const databaseId = merged.databaseId ?? process.env.NOTION_DATABASE_ID;
      const dryRun = merged.dryRun ?? false;

      if (!token) {
        throw new Error(
          "sink-notion requires a token. Set NOTION_TOKEN env var or config.token.",
        );
      }

      if (!databaseId) {
        throw new Error(
          "sink-notion requires a database ID. Set NOTION_DATABASE_ID env var or config.databaseId.",
        );
      }

      let delivered = 0;
      const errors: Array<{ result_index: number; error: string }> = [];

      for (const [index, result] of input.results.entries()) {
        if (!result.evidence || result.evidence.length === 0) {
          errors.push({
            result_index: index,
            error: `rejected: result without evidence cannot be delivered to Notion (id=${result.id})`,
          });
          continue;
        }

        if (dryRun) {
          console.log(`[sink-notion:dry-run] Would create page: "${result.title}"`);
          console.log(`  database: ${databaseId}`);
          console.log(`  type: ${result.type}, confidence: ${result.confidence}`);
          delivered += 1;
          continue;
        }

        try {
          const properties = buildPageProperties(result);
          const children = buildPageChildren(result);
          const page = await createNotionPage(token, databaseId, properties, children);
          console.log(`[sink-notion] Created page: ${page.url}`);
          delivered += 1;
        } catch (error) {
          errors.push({
            result_index: index,
            error: error instanceof Error ? error.message : String(error),
          });
        }
      }

      return {
        delivered,
        failed: errors.length,
        errors: errors.length > 0 ? errors : undefined,
      };
    },
  };
}

export default createNotionSink;
