import type { DeliveryReport, DistillResult, SinkPlugin } from "@loamlog/core";

export interface GitHubSinkConfig {
  /** GitHub API base URL. Default: https://api.github.com */
  apiBase?: string;
  /** GitHub personal access token (classic or fine-grained). */
  token?: string;
  /** Target repository in owner/repo format (e.g. "tongsh6/loamlog"). */
  repo?: string;
  /** Labels to apply to created issues. */
  labels?: string[];
  /** Dry run mode: log what would be created without actually calling the API. */
  dryRun?: boolean;
}

interface CreateIssueInput {
  title: string;
  body: string;
  labels: string[];
}

class GitHubAPIError extends Error {
  status: number;
  constructor(message: string, status: number) {
    super(message);
    this.name = "GitHubAPIError";
    this.status = status;
  }
}

async function createGitHubIssue(
  apiBase: string,
  token: string,
  owner: string,
  repo: string,
  input: CreateIssueInput,
): Promise<{ url: string; number: number }> {
  const url = `${apiBase}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/issues`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: JSON.stringify({
      title: input.title,
      body: input.body,
      labels: input.labels,
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    let message = `GitHub API error ${response.status}`;
    try {
      const parsed = JSON.parse(text) as { message?: string };
      if (parsed.message) message = parsed.message;
    } catch {
      message = text.slice(0, 200);
    }
    throw new GitHubAPIError(message, response.status);
  }

  const issue = (await response.json()) as { html_url: string; number: number };
  return { url: issue.html_url, number: issue.number };
}

function buildIssueBody(result: DistillResult): string {
  if (result.render?.markdown) {
    return result.render.markdown;
  }

  // Fallback: build a structured body from result fields
  const lines = [
    `## ${result.title}`,
    "",
    result.summary,
    "",
    "---",
    `**Confidence**: ${(result.confidence * 100).toFixed(0)}%`,
    `**Type**: ${result.type}`,
    `**Tags**: ${result.tags.join(", ")}`,
    "",
    "### Evidence",
  ];

  for (const evidence of result.evidence) {
    lines.push(`- Session \`${evidence.session_id}\` / Message \`${evidence.message_id}\``);
    lines.push(`  > ${evidence.excerpt.slice(0, 200)}`);
    lines.push(`  ${evidence.trace_command}`);
  }

  lines.push("", `*Generated by Loamlog @ ${result.distiller_id}*`);
  return lines.join("\n");
}

export function createGitHubSink(config: GitHubSinkConfig = {}): SinkPlugin {
  const apiBase = config.apiBase ?? "https://api.github.com";

  return {
    id: "@loamlog/sink-github",
    name: "GitHub Issue Sink",
    version: "0.1.0",

    supports(resultType: string): boolean {
      // Support common distiller output types
      return ["issue-draft", "pitfall-card", "todo-item"].includes(resultType);
    },

    async deliver(input: {
      results: DistillResult[];
      config: Record<string, unknown>;
    }): Promise<DeliveryReport> {
      // Merge construction-time config with delivery-time config (delivery wins)
      const merged: GitHubSinkConfig = { ...config, ...(input.config as GitHubSinkConfig) };
      const repoRaw = merged.repo ?? "";
      let token = merged.token ?? process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN;
      const labels = merged.labels ?? [];
      const dryRun = merged.dryRun ?? false;

      if (!repoRaw || !repoRaw.includes("/")) {
        throw new Error("sink-github requires config.repo in owner/repo format");
      }

      // Resolve token from gh CLI if not provided
      if (!token) {
        try {
          const { execSync } = await import("node:child_process");
          token = execSync("gh auth token", { encoding: "utf8", timeout: 5000 }).trim();
        } catch {
          throw new Error(
            "sink-github requires a token. Set GITHUB_TOKEN env var, config.token, or authenticate with `gh auth login`.",
          );
        }
      }

      if (!token) {
        throw new Error(
          "sink-github requires a token. Set GITHUB_TOKEN env var, config.token, or authenticate with `gh auth login`.",
        );
      }

      const [owner, repo] = repoRaw.split("/");

      let delivered = 0;
      const errors: Array<{ result_index: number; error: string }> = [];

      for (const [index, result] of input.results.entries()) {
        // Safety: reject results without evidence
        if (!result.evidence || result.evidence.length === 0) {
          errors.push({
            result_index: index,
            error: `rejected: result without evidence cannot be delivered to GitHub (id=${result.id})`,
          });
          continue;
        }

        const body = buildIssueBody(result);

        if (dryRun) {
          console.log(`[sink-github:dry-run] Would create issue: "${result.title}"`);
          console.log(`  repo: ${repoRaw}`);
          console.log(`  labels: ${labels.join(", ") || "(none)"}`);
          console.log(`  body: ${body.slice(0, 200)}...`);
          delivered += 1;
          continue;
        }

        try {
          const issue = await createGitHubIssue(apiBase, token, owner, repo, {
            title: result.title,
            body,
            labels: [...labels, ...result.tags],
          });
          console.log(`[sink-github] Created issue #${issue.number}: ${issue.url}`);
          delivered += 1;
        } catch (error) {
          errors.push({
            result_index: index,
            error: error instanceof Error ? error.message : String(error),
          });
        }
      }

      return {
        delivered,
        failed: errors.length,
        errors: errors.length > 0 ? errors : undefined,
      };
    },
  };
}

export default createGitHubSink;
